# Victoria Project - Docker Compose for API Service
version: '3.8'

services:
  # FastAPI Server Service - Main API
  api:
    build: .
    container_name: victoria-api
    ports:
      - "8000:8000"
    environment:
      - SERVICE_NAME=api
      - PYTHONPATH=/app
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DOCKER_ENV=true
      # Add your OpenAI API key here or use .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your-openai-key-here}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-2000}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.7}
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./responses.csv:/app/responses.csv:ro
      - ./trait.txt:/app/trait.txt:ro
      - ./templates:/app/templates:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - victoria-network

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: victoria-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: unless-stopped
    profiles: ["production"]
    networks:
      - victoria-network

# Named volumes for persistence
volumes:
  victoria_data:
    driver: local

# Network configuration
networks:
  victoria-network:
    driver: bridge